version: "3.8"
services:
  app:
    image: recipe-items:latest
    container_name: recipe-items
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    env_file:
      - .env
